language: swift
osx_image: xcode9.2
xcode_workspace: PlayerControls

before_install:
- brew update
- brew install sourcery
- bundle install
- cd SnapshotTests
- carthage update --platform iOS
- curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
- unzip awscli-bundle.zip
- sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
- aws configure set default.region eu-west-2
- aws configure set aws_access_key_id $AWS_ACCESS_KEY
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

script:
- cd ..
- fastlane test

after_failure:
- aws s3 rm --recursive s3://$S3_BUCKET/Failures/$TRAVIS_BRANCH/
- aws s3 cp ./SnapshotTests/Tests/FailureDifferences s3://$S3_BUCKET/Failures/$TRAVIS_BRANCH/ --recursive --include "*.jpg" --exclude "*.DS_Store" --acl public-read
- aws s3api list-objects --bucket aol-public --query 'Contents[].Key'  | tee keys.json

after_success:
- aws s3 rm --recursive s3://$S3_BUCKET/Failures/$TRAVIS_BRANCH/
