language: swift
osx_image: xcode9.2
xcode_workspace: PlayerControls

before_install:
- brew update
- brew install sourcery
- brew cask install fastlane
- cd SnapshotTests
- carthage update --platform iOS

script:
- cd ..
- fastlane test
